baseURL = "http://blog.gwurr3.me/"
languageCode = "en-us"
title = "/home/gwurr3"
theme = "gwurr3tech"
paginate = 11 # Number of posts to show before paginating


enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "gwurr3's personal blog" # Suggested, controls default description meta
  author = "gwurr3" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits
  images = [
    "https://avatars2.githubusercontent.com/u/3762920?v=4&s=460"
  ] # Suggested, controls default Open Graph images
  theme_variant = ""

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
